pub mod cache;
pub mod deadcode;
pub mod domain;
pub mod edit;
pub mod error;
pub mod external;
pub mod interfaces;
pub mod layers;
pub mod map;
pub mod modules;
pub mod plugins;
pub mod project;
pub mod respect_gitignore;
pub mod root_module;
pub mod rules;
pub mod utils;

pub use cache::{CacheBackend, CacheConfig};
pub use deadcode::{DeadcodeConfig, DeadcodeDetection};
pub use domain::{ConfigLocation, DomainConfig, LocatedDomainConfig};
pub use edit::ConfigEdit;
pub use error::ConfigError;
pub use external::ExternalDependencyConfig;
pub use interfaces::{InterfaceConfig, InterfaceDataTypes};
pub use layers::LayerConfig;
pub use map::MapConfig;
pub use modules::{DependencyConfig, ModuleConfig, serialize_modules_json};
pub use plugins::PluginsConfig;
pub use project::ProjectConfig;
pub use respect_gitignore::RespectGitIgnore;
pub use root_module::RootModuleTreatment;
pub use rules::{RuleSetting, RulesConfig};
