name: docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Install Dependencies
        run: ./pw uv sync --only-group docs
      - name: Build Documentation
        run: ./pw uv run zensical build --strict
  deploy:
    needs: build
    # Only deploy docs on pushes to main branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/checkout@v5
      - run: ./pw uv sync --only-group docs
      - run: ./pw uv run zensical build --clean 
      - uses: actions/upload-pages-artifact@v4
        with:
          path: site
      - uses: actions/deploy-pages@v4
        id: deployment